[package]
name = "im-common"
version = "0.1.0"
edition = "2021"

[dependencies]
etcd-client = { workspace = true }
anyhow = { workspace = true }
tokio = { workspace = true }
log = { workspace = true }
serde.workspace = true
serde_json = "1.0.134"


[lints]
workspace = true
